language: python

sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"
  - LUA="lua=5.1" PLUTFO="TRUE"
  - LUA="lua=5.2" PLUTFO="TRUE"
  - LUA="lua=5.3" PLUTFO="TRUE"
  - LUA="luajit=2.0" PLUTFO="TRUE"
  - LUA="luajit=2.1" PLUTFO="TRUE"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install luacheck
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
#  - luarocks install --server=http://luarocks.org/dev lutf8

script:
  - luacheck --no-unused-args --std max+busted *.lua spec #test tests
  - busted --verbose --coverage

after_success:
  - luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always